services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/blog
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data:
